# Use JDK (not JRE) for building and running
FROM eclipse-temurin:21-jdk-noble

# Install dependencies
RUN apt-get update \
  && apt-get install -y ca-certificates curl git openssh-client maven --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy only Maven files to download dependencies first
COPY pom.xml ./
COPY src ./src

# Install dependencies (optional pre-step)
RUN mvn dependency:go-offline

# Expose app port
EXPOSE 8080

# Default command for development
CMD ["mvn", "spring-boot:run"]
