-- Schema for Users table (Auto-generated by JPA usually, but provided here for reference)
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    username VARCHAR(100),
    password VARCHAR(100),
    firstname VARCHAR(100),
    lastname VARCHAR(100),
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    phone VARCHAR(20),
    "GoogleID" VARCHAR(255) UNIQUE,
    reset_token VARCHAR(255),
    reset_token_expiry TIMESTAMP
);
